build:
        tests:
                override:
                        -
                                command: ./gradlew test jacocoRootReport
                                coverage:
                                        file: 'build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml'
                                        format: 'jacoco'
